name: Archive build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'
      - '*.json'
      - '**/wcokey.txt'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "Archive-build"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate access token
      id: app-token
      uses: actions/create-github-app-token@v3
      with:
        client-id: ${{ vars.APP_CLIENT_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
        permission-contents: write
        repositories: |
          cloudstream-archive
          secrets

    - name: Get GitHub App User ID
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}

    - uses: actions/checkout@v6

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Fetch keystore
      id: fetch_keystore
      run: |
        TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
        mkdir -p "${TMP_KEYSTORE_FILE_PATH}"
        curl -H "Authorization: token ${{ steps.app-token.outputs.token }}" -o "${TMP_KEYSTORE_FILE_PATH}/prerelease_keystore.keystore" "https://raw.githubusercontent.com/${GITHUB_REPOSITORY_OWNER}/secrets/HEAD/keystore.jks"
        curl -H "Authorization: token ${{ steps.app-token.outputs.token }}" -o "keystore_password.txt" "https://raw.githubusercontent.com/${GITHUB_REPOSITORY_OWNER}/secrets/HEAD/keystore_password.txt"
        KEY_PWD="$(cat keystore_password.txt)"
        echo "::add-mask::${KEY_PWD}"
        echo "key_pwd=$KEY_PWD" >> $GITHUB_OUTPUT

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

    - name: Run Gradle
      run: ./gradlew assemblePrereleaseRelease
      env:
        SIGNING_KEY_ALIAS: "key0"
        SIGNING_KEY_PASSWORD: ${{ steps.fetch_keystore.outputs.key_pwd }}
        SIGNING_STORE_PASSWORD: ${{ steps.fetch_keystore.outputs.key_pwd }}
        SIMKL_CLIENT_ID: ${{ secrets.SIMKL_CLIENT_ID }}
        SIMKL_CLIENT_SECRET: ${{ secrets.SIMKL_CLIENT_SECRET }}
        MDL_API_KEY: ${{ secrets.MDL_API_KEY }}

    - uses: actions/checkout@v6
      with:
        repository: ${{ github.repository_owner }}/cloudstream-archive
        token: ${{ steps.app-token.outputs.token }}
        path: archive

    - name: Move build
      run: cp app/build/outputs/apk/prerelease/release/*.apk "archive/$(git rev-parse --short HEAD).apk"

    - name: Push archive
      run: |
        cd $GITHUB_WORKSPACE/archive
        git config --local user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
        git config --local user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
        git add .
        git commit -m "Build $GITHUB_SHA" || exit 0   # do not error if nothing to commit
        git push --force
