name: Dokka

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'

permissions:
  contents: read

concurrency:
  group: "dokka"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate access token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          permission-contents: write
          repositories: dokka

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: src

      - name: Checkout dokka
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/dokka
          token: ${{ steps.app-token.outputs.token }}
          path: dokka

      - name: Clean old builds
        run: |
          cd $GITHUB_WORKSPACE/dokka/
          rm -rf "./app"
          rm -rf "./library"

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Generate Dokka
        run: |
          cd $GITHUB_WORKSPACE/src/
          chmod +x gradlew
          ./gradlew docs:dokkaGeneratePublicationHtml

      - name: Copy Dokka
        run: cp -r $GITHUB_WORKSPACE/src/docs/build/dokka/html/* $GITHUB_WORKSPACE/dokka/

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/dokka
          touch .nojekyll
          git config --local user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          git config --local user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git add .
          git commit -m "Generate dokka for ${GITHUB_REPOSITORY}@${GITHUB_SHA}" || exit 0   # do not error if nothing to commit
          git push --force
