name: Pre-release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'
      - '*.json'
      - '**/wcokey.txt'

concurrency:
  group: "pre-release"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Keystore
      run: |
        TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
        mkdir -p "${TMP_KEYSTORE_FILE_PATH}"
        cp keystore.jks "${TMP_KEYSTORE_FILE_PATH}/prerelease_keystore.keystore"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Run Gradle
      run: ./gradlew assemblePrereleaseRelease androidSourcesJar makeJar > gradle.log 2>&1 || (cat gradle.log ; exit 1)
      env:
        SIGNING_KEY_ALIAS: "key0"
        SIGNING_KEY_PASSWORD: "cloudstream"
        SIGNING_STORE_PASSWORD: "cloudstream"
        MDBLIST_API_KEY: "aorzuy9py52y89nl78oaoskad"

    - name: Push Logs
      if: failure()
      run: |
        git config --global user.email "bot@example.com"
        git config --global user.name "Bot"
        git fetch
        git checkout -b build-logs
        git add gradle.log
        git commit -m "Add build logs"
        git push origin build-logs -f

    - name: Create pre-release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "pre-release"
        prerelease: true
        title: "Pre-release Build"
        files: |
          app/build/outputs/apk/prerelease/release/*.apk
          app/build/libs/app-sources.jar
          app/build/classes.jar
