name: Fix locale issues

on:
  push:
    branches: [ master ]
    paths:
      - '**.xml'
  workflow_dispatch:

concurrency:
  group: "locale"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Generate access token
      id: app-token
      uses: actions/create-github-app-token@v3
      with:
        client-id: ${{ vars.APP_CLIENT_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        permission-contents: write

    - name: Get GitHub App User ID
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}

    - uses: actions/checkout@v6
      with:
        token: ${{ steps.app-token.outputs.token }}

    - name: Install dependencies
      run: pip3 install lxml requests

    - name: Edit files
      run: python3 .github/locales.py

    - name: Commit to the repo
      run: |
        git config --local user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
        git config --local user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
        git add .
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -m 'chore(locales): fix locale issues' || echo
        git push
